### ISSUE TITLE
Nonsensical test cases

### ISSUE THREAD

**Issue by Engelberg** [mashooq/katas#3]
Several of these test cases seem flawed.

For example, ` (is (= 99 (score "91919393929291219191"))))`
doesn't make a whole lot of sense.  How can you knock down 9 pins with the first ball and 3 pins with the second ball when there are only 10 pins?

**Comment by Engelberg** [comment]
P.S. You might be interested in my 11-line version (which passes all the valid test cases in your test suite)
https://gist.github.com/Engelberg/d93ea307fa5c8f1337a4ac7566df7f9d

**Comment by mashooq** [comment]
Thanks - the purpose of my solution was not to do in in the smallest line possible. Agree with the test case comment.
